### ISSUE TITLE
In local version, deleted tags are still in the facet

### ISSUE THREAD

**Issue by Soliine** [ICIJ/datashare#299]
I am on Mac OS 10.14.6. I tagged three times a document when I used an older version Datashare. I had deleted the tags from the documents. The three tags remained in the facet and helped me filter the document that used to be tagged. I downloaded the last version of Datashare (4.17.9). The tags remain here and still allow to filter the previously tagged document.
<img width="1427" alt="Screenshot 2019-11-07 at 15 24 28" src="https://user-images.githubusercontent.com/17233829/68397027-d0d8f380-0172-11ea-905c-386bd2b559bf.png">

**Comment by arthcras** [comment]
> I am on Mac OS 10.14.6. I tagged three times a document when I used an older version Datashare. I had deleted the tags from the documents. The three tags remained in the facet and helped me filter the document that used to be tagged. I downloaded the last version of Datashare (4.17.9). The tags remain here and still allow to filter the previously tagged document.
> <img alt="Screenshot 2019-11-07 at 15 24 28" width="1427" src="https://user-images.githubusercontent.com/17233829/68397027-d0d8f380-0172-11ea-905c-386bd2b559bf.png">

I believe i have a similar issue, i also delete the document, but the document stil appear

**Comment by annelhote** [comment]
The point is that the ES change in the index (tag deletion) is not immediately visible for the search :
https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-refresh.html

**Comment by arthcras** [comment]
Thanks for the clarification
Best rgds
Arthur


Verstuurd vanaf mijn iPhone

**Comment by annelhote** [comment]
@arthcras It should be fixed since Datashare version 4.21.8.

**Comment by arthcras** [comment]
HI Team
Just installed version 4.21.8.  server is up, but documents still not found, while they are in the folder. Have attached log file. Could you see what is the issue. If you need more info kindly let me know.
Cheers
Arthur

SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/home/datashare/lib/datashare-nlp-opennlp-4.21.8-jar-with-dependencies.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/home/datashare/lib/datashare-nlp-mitie-4.21.8-jar-with-dependencies.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/home/datashare/lib/datashare-nlp-ixapipe-4.21.8-jar-with-dependencies.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/home/datashare/lib/datashare-nlp-corenlp-4.21.8-jar-with-dependencies.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/home/datashare/lib/datashare-db-4.21.8-jar-with-dependencies.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/home/datashare/lib/datashare-app-4.21.8-jar-with-dependencies.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
09:03:27,898 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback.groovy]
09:03:27,899 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback-test.xml]
09:03:27,903 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Found resource [logback.xml] at [jar:file:/home/datashare/lib/datashare-nlp-opennlp-4.21.8-jar-with-dependencies.jar!/logback.xml]
09:03:27,906 |-WARN in ch.qos.logback.classic.LoggerContext[default] - Resource [logback.xml] occurs multiple times on the classpath.
09:03:27,907 |-WARN in ch.qos.logback.classic.LoggerContext[default] - Resource [logback.xml] occurs at [jar:file:/home/datashare/lib/datashare-app-4.21.8-jar-with-dependencies.jar!/logback.xml]
09:03:27,907 |-WARN in ch.qos.logback.classic.LoggerContext[default] - Resource [logback.xml] occurs at [jar:file:/home/datashare/lib/datashare-nlp-mitie-4.21.8-jar-with-dependencies.jar!/logback.xml]
09:03:27,907 |-WARN in ch.qos.logback.classic.LoggerContext[default] - Resource [logback.xml] occurs at [jar:file:/home/datashare/lib/datashare-nlp-corenlp-4.21.8-jar-with-dependencies.jar!/logback.xml]
09:03:27,907 |-WARN in ch.qos.logback.classic.LoggerContext[default] - Resource [logback.xml] occurs at [jar:file:/home/datashare/lib/datashare-nlp-ixapipe-4.21.8-jar-with-dependencies.jar!/logback.xml]
09:03:27,907 |-WARN in ch.qos.logback.classic.LoggerContext[default] - Resource [logback.xml] occurs at [jar:file:/home/datashare/lib/datashare-nlp-opennlp-4.21.8-jar-with-dependencies.jar!/logback.xml]
09:03:28,011 |-INFO in ch.qos.logback.core.joran.spi.ConfigurationWatchList@6979e8cb - URL [jar:file:/home/datashare/lib/datashare-nlp-opennlp-4.21.8-jar-with-dependencies.jar!/logback.xml] is not of type file
09:03:28,356 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - debug attribute not set
09:03:28,382 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.ConsoleAppender]
09:03:28,416 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [STDOUT]
09:03:28,444 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
09:03:28,783 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.rolling.RollingFileAppender]
09:03:28,797 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [FILE]
09:03:28,857 |-INFO in c.q.l.core.rolling.TimeBasedRollingPolicy@1983747920 - No compression will be used
09:03:28,865 |-INFO in c.q.l.core.rolling.TimeBasedRollingPolicy@1983747920 - Will use the pattern ./logs/datashare_opennlp.%d{yyyy-MM-dd}.log for the active file
09:03:28,897 |-INFO in c.q.l.core.rolling.DefaultTimeBasedFileNamingAndTriggeringPolicy - The date pattern is 'yyyy-MM-dd' from file name pattern './logs/datashare_opennlp.%d{yyyy-MM-dd}.log'.
09:03:28,897 |-INFO in c.q.l.core.rolling.DefaultTimeBasedFileNamingAndTriggeringPolicy - Roll-over at midnight.
09:03:28,910 |-INFO in c.q.l.core.rolling.DefaultTimeBasedFileNamingAndTriggeringPolicy - Setting initial period to Wed Nov 27 09:02:28 GMT 2019
09:03:28,914 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
09:03:28,928 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[FILE] - Active log file name: ./logs/datashare.log
09:03:28,928 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[FILE] - File property is set to [./logs/datashare.log]
09:03:28,933 |-INFO in ch.qos.logback.classic.joran.action.RootLoggerAction - Setting level of ROOT logger to INFO
09:03:28,934 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [STDOUT] to Logger[ROOT]
09:03:28,936 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [FILE] to Logger[ROOT]
09:03:28,937 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - End of configuration.
09:03:28,943 |-INFO in ch.qos.logback.classic.joran.JoranConfigurator@5c0369c4 - Registering current configuration as safe fallback point
2019-11-27T09:03:28.965082400Z 
SLF4J: Actual binding is of type [ch.qos.logback.classic.util.ContextSelectorStaticBinder]
2019-11-27 09:03:29,702 [main] INFO  Main - Running datashare web server
2019-11-27 09:03:29,789 [main] WARN  PropertiesProvider - no null file found, using default values
2019-11-27 09:03:29,798 [main] INFO  PropertiesProvider - properties set to {}
2019-11-27 09:03:29,799 [main] INFO  PropertiesProvider - merged properties (without override) with {tcpListenPort=8080, stages=SCAN,INDEX,NLP, elasticsearchAddress=http://elasticsearch:9200, queueName=extract:queue, sessionTtlSeconds=43200, protectedUriPrefix=/api/, cors=no-cors, mode=LOCAL, redisAddress=redis://redis:6379, defaultUserName=local, ocr=true, nlpParallelism=1, parserParallelism=1, dataSourceUrl=jdbc:sqlite:/home/datashare/dist/database.sqlite, dataDir=/home/datashare/data, defaultProject=local-datashare, clusterName=datashare, messageBusAddress=redis, parallelism=2}
2019-11-27 09:03:33,565 [main] INFO  HikariDataSource - HikariPool-1 - Starting...
2019-11-27 09:03:34,065 [main] INFO  HikariDataSource - HikariPool-1 - Start completed.
2019-11-27 09:03:34,266 [main] INFO  HikariDataSource - HikariPool-2 - Starting...
2019-11-27 09:03:34,286 [main] INFO  HikariDataSource - HikariPool-2 - Start completed.
2019-11-27 09:03:34,642 [main] INFO  HikariDataSource - HikariPool-3 - Starting...
2019-11-27 09:03:34,674 [main] INFO  HikariDataSource - HikariPool-3 - Start completed.
2019-11-27 09:03:46,333 [main] INFO  JdbcExecutor - SELECT COUNT(*) FROM DATABASECHANGELOGLOCK
2019-11-27 09:03:46,454 [main] INFO  JdbcExecutor - SELECT COUNT(*) FROM DATABASECHANGELOGLOCK
2019-11-27 09:03:46,505 [main] INFO  JdbcExecutor - SELECT LOCKED FROM DATABASECHANGELOGLOCK WHERE ID=1
2019-11-27 09:03:46,758 [main] INFO  StandardLockService - Successfully acquired change log lock
2019-11-27 09:03:52,569 [main] INFO  JdbcExecutor - SELECT MD5SUM FROM DATABASECHANGELOG WHERE MD5SUM IS NOT NULL
2019-11-27 09:03:52,581 [main] INFO  JdbcExecutor - SELECT COUNT(*) FROM DATABASECHANGELOG
2019-11-27 09:03:52,589 [main] INFO  StandardChangeLogHistoryService - Reading from DATABASECHANGELOG
2019-11-27 09:03:52,596 [main] INFO  JdbcExecutor - SELECT * FROM DATABASECHANGELOG ORDER BY DATEEXECUTED ASC, ORDEREXECUTED ASC
2019-11-27 09:03:52,929 [main] INFO  StandardLockService - Successfully released change log lock
2019-11-27 09:03:52,940 [main] INFO  HikariDataSource - HikariPool-3 - Shutdown initiated...
2019-11-27 09:03:53,080 [main] INFO  HikariDataSource - HikariPool-3 - Shutdown completed.
2019-11-27 09:03:54,225 [main] INFO  Indexer - indexer defined with cfg{indexType='doc', indexJoinField='join', docTypeField='type', shards=1, replicas=1}
2019-11-27 09:03:55,375 [pool-3-thread-1] INFO  IndexWaiterFilter - Ping elasticsearch succeeded
2019-11-27 09:03:56,890 [main] INFO  Fluent - Production mode
2019-11-27 09:03:57,379 [main] INFO  Fluent - Server started on port 8080

**Comment by annelhote** [comment]
Hi @arthcras, it seems that your last comment is more related to issue #311 than this issue. I will copy/paste your message in it.
Thanks.

**Comment by arthcras** [comment]
Ok thanks

Verstuurd vanaf mijn iPhone
